{
 "title": "Kafka Broker 2 req Metrics",
 "description": "Metrics for Kafka req Broker 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Kafka Broker 2 req Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_messages_in_per_sec{instance=\"kafka-2-reg:7072\"}[5m])",
     "legendFormat": "Broker req 2"
    }
   ]
  },
  {
   "title": "Bytes In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_bytes_in_per_sec{instance=\"kafka-2-reg:7072\"}[5m])",
     "legendFormat": "Broker req 2"
    }
   ]
  },
  {
   "title": "Network Processor Idle Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_processor_idle_percent{instance=\"kafka-2-reg:7072\"}",
     "legendFormat": "Broker req 2"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_under_replicated_partitions{instance=\"kafka-2-reg:7072\"}",
     "legendFormat": "Broker req 2"
    }
   ]
  }
 ]
}