{
 "title": "Kafka Cluster destination metrics",
 "description": "Aggregated metrics from all Kafka destination brokers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Cluster destination Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Messages In Per Second (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_messages_in_per_sec{cluster=\"kafka-destination\"}[5m])) by (cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Bytes In Per Second (Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_bytes_in_per_sec{cluster=\"kafka-destination\"}[5m])) by (cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Processor Idle Percent (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_processor_idle_percent{cluster=\"kafka-destination\"}) by (cluster)",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions (Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_under_replicated_partitions{cluster=\"kafka-destination\"}) by (cluster)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}