global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'app-receiver'

receivers:
  - name: 'app-receiver'
    webhook_configs:
      - url: 'http://app:8090/api/alerts'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'instance']